### ISSUE TITLE
but broke

### ISSUE THREAD

**Issue by amanalar** [haste/Butsu#7]
I've been playing that long, that I still use butsu. 

a long run but now finally broke :(

2x Butsu\butsu-2.1.1.lua:45: attempt to index local 'color' (a nil value)
Butsu\butsu-2.1.1.lua:45: in function `?'
Butsu\butsu-2.1.1.lua:6: in function <Butsu\butsu.lua:5>

Locals:
self = Butsu {
 0 = <userdata>
 LOOT_CLOSED = <function> defined @Butsu\butsu.lua:119
 LOOT_OPENED = <function> defined @Butsu\butsu.lua:9
 LoadPosition = <function> defined @Butsu\butsu.lua:153
 OPEN_MASTER_LOOT_LIST = <function> defined @Butsu\butsu.lua:129
 UPDATE_MASTER_LOOT_LIST = <function> defined @Butsu\butsu.lua:134
 title = <unnamed> {
 }
 AnchorSlots = <function> defined @Butsu\slots.lua:145
 LOOT_SLOT_CLEARED = <function> defined @Butsu\butsu.lua:111
 UpdateWidth = <function> defined @Butsu\slots.lua:131
 SavePosition = <function> defined @Butsu\butsu.lua:144
}
event = "LOOT_OPENED"
autoloot = true
L = <table> {
 uiFrameScale = "Frame scale"
 uiCountSize = "Count"
 uiTitleSize = "Title"
 fish = "Fishy loot"
 uiIconSize = "Icon size"
 uiItemSize = "Item"
 empty = "Empty slot"
 uiScaleSizeTitle = "Scale and size"
 uiFontSizeTitle = "Font size"
}
m = 0
items = 1
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
slot = ButsuSlot1 {
 0 = <userdata>
 count = <unnamed> {
 }
 iconFrame = <unnamed> {
 }
 drop = <unnamed> {
 }
 name = <unnamed> {
 }
 icon = <unnamed> {
 }
 quest = <unnamed> {
 }
}
texture = 133787
item = "37 Silver
8 Copper"
quantity = 0
quality = nil
locked = 1
isQuestItem = false
questId = false
isActive = nil
color = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'color' (a nil value)"
_NS = <table> {
 db = <table> {
 }
 L = <table> {
 }
 slots = <table> {
 }
 CreateSlot = <function> defined @Butsu\slots.lua:61
}

**Comment by haste** [comment]
I pushed some changes based on the FrameXML. Don't really play anymore so just report back :)

**Comment by amanalar** [comment]
Cool I'll check it out when I get home. In the meantime

*cough

Now is the perfect time to play World of Warcraft
[https://www.polygon.com/2018/7/19/17588576/world-of-warcraft-returning-player](url)

**Comment by haste** [comment]
I pushed a release to WoWI. Thanks for testing. :)
