### ISSUE TITLE
Error since 8.1.5

### ISSUE THREAD

**Issue by Winney1907** [haste/Butsu#8]
Date: 2019-03-25 14:54:11
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Butsu\slots.lua line 25:
   attempt to compare number with nil
Debug:
   Butsu\slots.lua:25:
      Butsu\slots.lua:24
Locals:
self = ButsuSlot3 {
 0 = <userdata>
 count = <unnamed> {
 }
 iconFrame = <unnamed> {
 }
 drop = <unnamed> {
 }
 name = <unnamed> {
 }
 icon = <unnamed> {
 }
 quest = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"

**Comment by Yzou-NaO** [comment]
I think this still can't work, the bug happened when you are master looter.
28x Blizzard_SharedXML/Classic/UIDropDownMenu.lua:1004: attempt to index local 'button' (a nil value)
[Blizzard_SharedXML/Classic/UIDropDownMenu.lua]:1004: in function 'ToggleDropDownMenu'
[Butsu/butsu.lua]:135: in function '?'
[Butsu/butsu.lua]:6: in function <Butsu/butsu.lua:5>
[C]: in function 'LootSlot'
[Butsu/slots.lua]:49: in function <Butsu/slots.lua:38>

Locals:
level = 1
value = nil
dropDownFrame = nil
anchorName = ButsuSlot2 {
 icon = Texture {
 }
 isQuestItem = false
 name = FontString {
 }
 drop = Texture {
 }
 count = FontString {
 }
 iconFrame = Frame {
 }
 quest = Texture {
 }
 quality = 2
}
xOffset = 0
yOffset = 0
menuList = nil
button = nil
autoHideDelay = nil
listFrame = DropDownList1 {
 dropdown = Frame {
 }
 shouldRefresh = true
 numButtons = 0
 maxWidth = 0
}
listFrameName = "DropDownList1"
tempFrame = nil
point = nil
relativePoint = nil
relativeTo = nil
(*temporary) = nil
(*temporary) = "createframes"
(*temporary) = true
(*temporary) = 1
(*temporary) = 0
(*temporary) = 10
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'button' (a nil value)"
UIDropDownMenuDelegate = Frame {
}
envTable = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 798
 BuyEmAllFrameTopTex = BuyEmAllFrameTopTex {
 }
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 413
 BT4Button58 = BT4Button58 {
 }
 InspectFrameTab1HighlightTexture = InspectFrameTab1HighlightTexture {
 }
 ContainerFrame3Item34SubIconTexture = ContainerFrame3Item34SubIconTexture {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 CompactRaidGroup1Member4OverHealAbsorbGlow = CompactRaidGroup1Member4OverHealAbsorbGlow {
 }
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 365
 MerchantItem4AltCurrencyFrameItem1Text = MerchantItem4AltCurrencyFrameItem1Text {
 }
 OPTION_SHOW_ACTION_BAR5_TOOLTIP = "Attached to the left side of Action Bar 4 by default"
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 table: 000001763295E250Icon = table: 000001763295E250Icon {
 }
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 BCM_History_SetHigh = BCM_History_SetHigh {
 }
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 1018
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 33
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 PallyPowerBlessingsFramePlayer13Line5 = PallyPowerBlessingsFramePlayer13Line5 {
 }
 TrinketMenu_Trinket1Shine13 = TrinketMenu_Trinket1Shine13 {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 LibDBIcon10_BugSack = LibDBIcon10_BugSack {
 }
 CompactUnitFrameProfilesSaveButton = CompactUnitFrameProfilesSaveButton {
 }
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 PetPaperDollFrameTab3Right = PetPaperDollFrameTab3Right {
 }
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle {
 }
 ContainerFrame4Item16Cooldown = ContainerFrame4Item16Cooldown {
 }
 AtlasEntry17 = AtlasEntry17 {
 }
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 LAG_TOLERANCE = "Lag Tolerance"
 GuildControlPopupFrame = GuildControlPopupFrame {
 }
 SendStationeryBackgroundRight = SendStationeryBackgroundRight {
 }
 TUTORIAL61_SPELLID_DRUID = "768"
 MultiBarLeftButton9Border = MultiBarLeftButton9Border {
 }
 LE_GAME_ERR_NOT_ON_TOURNAMENT_REALM = 900
 UIWidgetCenterDisplayFrameText = UIWidgetCenterDisplayFrameText {
 }
 TrinketMenu_Menu30Shine7 = TrinketMenu_Menu30Shine7 {
 }
 ItemRackButton12Cooldown = ItemRackButton12Cooldown {
 }
 TrinketMenu_Menu16Name = TrinketMenu_Menu16Name {
 }
 OPTION_TOOLTIP_SHOW_ACCOUNT_ACHIEVEMENTS = "Turning this option on will only display your character achievements when people inspect you or use the Blizzard website or mobile app."
 SPIRIT_HEALER_RELEASE_RED = "|cffff2020Spirit Healer|r"
 SpellActivationOverlayOptionsPanelGlowingButtons = SpellAct
